### PR TITLE
Upgrade package due to security flaw in eslint-utils@1.4.1

### PR DESCRIPTION
**Pull request by majoravery**
See https://github.com/titel-media/react-apollo-multiple-clients/network/alert/yarn.lock/eslint-utils/open and

### CODE REVIEW

**Comment by dazlious** [comment]
why the next major? have you run `yarn upgrade-interactive`?

**Comment by dazlious** [comment]
we can also use the `resolutions` options in package.json

**Comment by dazlious** [comment]
have you tested that linting still works? If yes, we can ofc merge this

**Review by dazlious — APPROVED** [review]

**Comment by majoravery** [comment]
Because that's the only one that has a version of eslint-utils more than 1.4.1 https://github.com/eslint/eslint/pull/12131. Also I didn't know about `resolutions`!

**Pull request merged**
